/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	allSemsSidebar: [{ type: 'autogenerated', dirName: '.' }],
	sem1Sidebar: [{ type: 'autogenerated', dirName: 'sem1' }],
	sem2Sidebar: [{ type: 'autogenerated', dirName: 'sem2' }],
	sem3Sidebar: [{ type: 'autogenerated', dirName: 'sem3' }],
	sem4Sidebar: [{ type: 'autogenerated', dirName: 'sem4' }],
	sem5Sidebar: [{ type: 'autogenerated', dirName: 'sem5' }],
	sem6Sidebar: [{ type: 'autogenerated', dirName: 'sem6' }],
	sem7Sidebar: [{ type: 'autogenerated', dirName: 'sem7' }],
	sem8Sidebar: [{ type: 'autogenerated', dirName: 'sem8' }],
	aiSidebar: [
		{ type: 'autogenerated', dirName: 'sem7/artificial-intelligence' },
	],
	ccSidebar: [{ type: 'autogenerated', dirName: 'sem7/cloud-computing' }],
	// ccSidebar: [
	//   'intro',
	//   'hello',
	//   {
	//     type: 'category',
	//     label: 'Tutorial',
	//     items: ['tutorial-basics/create-a-document'],
	//   },
	// ],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
